---
title: "Some examples"
author: "Frederic Bertrand"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r}
install.packages("Epi")
```

```{r}
library(sgPLS)
library(plsRcox)
```

## Deviance residuals

```{r}
## Simulation of datasets X and Y with group variables
library(plsRcox)
data(micro.censure)
Y_train_micro <- micro.censure$survyear[1:80]
C_train_micro <- micro.censure$DC[1:80]

Y_DR <- computeDR(Y_train_micro,C_train_micro)
```

## gPLS
```{r}
data(Xmicro.censure_compl_imp)
X_train_micro <- apply((as.matrix(Xmicro.censure_compl_imp)),FUN="as.numeric",MARGIN=2)[1:80,]
X_train_micro_df <- data.frame(X_train_micro)

model.gPLS <- gPLS(X_train_micro_df, Y_DR, ncomp = 2, mode = "regression", keepX = c(4, 4), keepY = 4, ind.block.x =1)

result.gPLS <- select.sgpls(model.gPLS)
result.gPLS$group.size.X
result.gPLS$group.size.Y

tt_pls <- data.frame(model.gPLS$variates$X)
if (model.gPLS$ncomp > 0) {
        colnames(tt_pls) <- paste("dim", 1:ncol(tt_pls), sep = ".")
}
```


## sgPLS

```{r}
library(sgPLS)
library(plsRcox)
data(micro.censure)
data(Xmicro.censure_compl_imp)

X_train_micro <- apply((as.matrix(Xmicro.censure_compl_imp)),FUN="as.numeric",MARGIN=2)[1:80,]
X_train_micro_df <- data.frame(X_train_micro)
Y_train_micro <- micro.censure$survyear[1:80]
C_train_micro <- micro.censure$DC[1:80]

Y_DR <- computeDR(Y_train_micro,C_train_micro)

#### sgPLS model
model.sgPLS <- sgPLS(X_train_micro_df, Y_DR, ncomp = 2, mode = "regression", keepX = c(4, 4), keepY = 4, ind.block.x = 1, alpha.x = c(0.95, 0.95), alpha.y = c(0.95, 0.95))

result.sgPLS <- select.sgpls(model.sgPLS)
result.sgPLS$group.size.X
result.sgPLS$group.size.Y
```



```{r}
library(bigsgPLS)
```


## bigPLScox

```{r}
library(plsRcox)
data(micro.censure)
data(Xmicro.censure_compl_imp)

X_train_micro <- apply((as.matrix(Xmicro.censure_compl_imp)),FUN="as.numeric",MARGIN=2)[1:80,]
X_train_micro_df <- data.frame(X_train_micro)
Y_train_micro <- micro.censure$survyear[1:80]
C_train_micro <- micro.censure$DC[1:80]

Y_DR <- computeDR(Y_train_micro,C_train_micro)

library(bigmemory)
X.bm <- as.big.matrix(X_train_micro_df)
y.bm <- as.big.matrix(Y_DR)

library(doParallel)
registerDoParallel(cores = 2)
getDoParWorkers()
fit.PLS <- bigsgpls(X.bm, y.bm, case = 4, H = 4, ng = 10, keepX = rep(5,4), regularised = "none")
pred.fit <- predict(fit.PLS, newX = X_train_micro, ng = 1)
round(pred.fit$Beta,3)
```

## bigsPLS

```{r}
library(plsRcox)
data(micro.censure)
data(Xmicro.censure_compl_imp)

X_train_micro <- apply((as.matrix(Xmicro.censure_compl_imp)),FUN="as.numeric",MARGIN=2)[1:80,]
X_train_micro_df <- data.frame(X_train_micro)
Y_train_micro <- micro.censure$survyear[1:80]
C_train_micro <- micro.censure$DC[1:80]

Y_DR <- computeDR(Y_train_micro,C_train_micro)

library(bigmemory)
X.bm <- as.big.matrix(X_train_micro_df)
y.bm <- as.big.matrix(Y_DR)

library(doParallel)
registerDoParallel(cores = 2)
getDoParWorkers()
fit.PLS <- bigsgpls(X.bm, y.bm, case = 4, H = 4, ng = 10, keepX = rep(5,4), regularised = "sparse")
pred.fit <- predict(fit.PLS, newX = X_train_micro, ng = 1)
round(pred.fit$Beta,3)
```

## biggPLS

```{r}
library(plsRcox)
data(micro.censure)
data(Xmicro.censure_compl_imp)

X_train_micro <- apply((as.matrix(Xmicro.censure_compl_imp)),FUN="as.numeric",MARGIN=2)[1:80,]
X_train_micro_df <- data.frame(X_train_micro)
Y_train_micro <- micro.censure$survyear[1:80]
C_train_micro <- micro.censure$DC[1:80]

Y_DR <- computeDR(Y_train_micro,C_train_micro)

library(bigmemory)
X.bm <- as.big.matrix(X_train_micro_df)
y.bm <- as.big.matrix(Y_DR)

library(doParallel)
registerDoParallel(cores = 2)
getDoParWorkers()
fit.PLS <- bigsgpls(X.bm, y.bm, case = 4, H = 4, ng = 10, keepX = rep(5,4), regularised = "group")
pred.fit <- predict(fit.PLS, newX = X_train_micro, ng = 1)
round(pred.fit$Beta,3)
```

## bigsgPLS

```{r}
library(plsRcox)
data(micro.censure)
data(Xmicro.censure_compl_imp)

X_train_micro <- apply((as.matrix(Xmicro.censure_compl_imp)),FUN="as.numeric",MARGIN=2)[1:80,]
X_train_micro_df <- data.frame(X_train_micro)
Y_train_micro <- micro.censure$survyear[1:80]
C_train_micro <- micro.censure$DC[1:80]

Y_DR <- computeDR(Y_train_micro,C_train_micro)

library(bigmemory)
X.bm <- as.big.matrix(X_train_micro_df)
y.bm <- as.big.matrix(Y_DR)

library(doParallel)
registerDoParallel(cores = 2)
getDoParWorkers()
fit.PLS <- bigsgpls(X.bm, y.bm, case = 4, H = 4, ng = 10, keepX = rep(5,4), regularised = "sparse group")
pred.fit <- predict(fit.PLS, newX = X_train_micro, ng = 1)
round(pred.fit$Beta,3)
```


```{r, eval=FALSE}
bigscale
data(survData, package="bigSurvSGD")
resultsBig <- bigscale(data=survData, parallel.flag=TRUE, num.cores=2)
resultsBig
```




