# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pls_big_cpp <- function(xpMat, Y, ncomp, tol = 1e-6, max_iter = 500L) {
    .Call('_bigPLS_pls_big_cpp', PACKAGE = 'bigPLS', xpMat, Y, ncomp, tol, max_iter)
}

