# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

big_pls_cox_col_stats_cpp <- function(xpMat) {
    .Call(`_bigPLScox_big_pls_cox_col_stats_cpp`, xpMat)
}

big_pls_cox_component_cpp <- function(xpMat, residuals, scores_prev, loadings_prev, means, sds) {
    .Call(`_bigPLScox_big_pls_cox_component_cpp`, xpMat, residuals, scores_prev, loadings_prev, means, sds)
}

big_pls_cox_gd_cpp <- function(X_ptr, time, status, ncomp, max_iter, tol, learning_rate) {
    .Call(`_bigPLScox_big_pls_cox_gd_cpp`, X_ptr, time, status, ncomp, max_iter, tol, learning_rate)
}

